use apex_core::{
    error::{ApexError, Result},
    traits::TestSynthesizer,
    types::{Language, SynthesizedTest, TestCandidate},
};
use std::{collections::HashSet, path::PathBuf};
use tracing::info;

pub struct PytestSynthesizer {
    output_dir: PathBuf,
}

impl PytestSynthesizer {
    pub fn new(output_dir: impl Into<PathBuf>) -> Self {
        PytestSynthesizer {
            output_dir: output_dir.into(),
        }
    }

    fn generate_file_content(candidates: &[&TestCandidate]) -> String {
        let mut content = String::new();

        // Header
        content.push_str("# Auto-generated by APEX — do not edit by hand.\n");
        content.push_str("# Each test targets specific uncovered branches.\n\n");
        content.push_str("import pytest\n\n");

        for (i, candidate) in candidates.iter().enumerate() {
            if !candidate.code.trim().is_empty() {
                content.push_str(&format!(
                    "# Candidate {} — targets: {}\n",
                    i + 1,
                    candidate
                        .target_branches
                        .iter()
                        .map(|b| format!("{}:{}", b.file_id, b.line))
                        .collect::<Vec<_>>()
                        .join(", ")
                ));
                content.push_str(&candidate.code);
                content.push_str("\n\n");
            }
        }

        content
    }
}

impl TestSynthesizer for PytestSynthesizer {
    fn language(&self) -> Language {
        Language::Python
    }

    fn synthesize(&self, candidates: &[TestCandidate]) -> Result<Vec<SynthesizedTest>> {
        if candidates.is_empty() {
            return Ok(Vec::new());
        }

        // Deduplicate by code hash.
        let mut seen_hashes: HashSet<u64> = HashSet::new();
        let mut unique: Vec<&TestCandidate> = Vec::new();
        for c in candidates {
            use std::hash::{Hash, Hasher};
            let mut hasher = std::collections::hash_map::DefaultHasher::new();
            c.code.hash(&mut hasher);
            let h = hasher.finish();
            if seen_hashes.insert(h) {
                unique.push(c);
            }
        }

        // Write in batches of 20 candidates per file.
        let chunk_size = 20;
        let mut outputs = Vec::new();

        for chunk in unique.chunks(chunk_size) {
            let content = Self::generate_file_content(chunk);
            let hash: u64 = {
                use std::hash::{Hash, Hasher};
                let mut h = std::collections::hash_map::DefaultHasher::new();
                content.hash(&mut h);
                h.finish()
            };
            let file_name = format!("test_apex_{hash:016x}.py");
            let file_path = self.output_dir.join("apex_generated").join(&file_name);

            let parent = file_path
                .parent()
                .ok_or_else(|| ApexError::Synthesis("file path has no parent dir".into()))?;
            std::fs::create_dir_all(parent)
                .map_err(|e| ApexError::Synthesis(format!("create dir: {e}")))?;

            std::fs::write(&file_path, &content)
                .map_err(|e| ApexError::Synthesis(format!("write {file_name}: {e}")))?;

            let covers: Vec<_> = chunk
                .iter()
                .flat_map(|c| c.target_branches.clone())
                .collect();

            info!(file = %file_path.display(), candidates = chunk.len(), "wrote test file");

            outputs.push(SynthesizedTest {
                path: file_path,
                content,
                covers_branches: covers,
            });
        }

        Ok(outputs)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use apex_core::types::BranchId;

    fn make_candidate(code: &str, branches: Vec<BranchId>) -> TestCandidate {
        let mut tc = TestCandidate::new(code.to_string(), Language::Python);
        tc.target_branches = branches;
        tc
    }

    #[test]
    fn empty_candidates_returns_empty() {
        let dir = tempfile::tempdir().unwrap();
        let synth = PytestSynthesizer::new(dir.path());
        let result = synth.synthesize(&[]).unwrap();
        assert!(result.is_empty());
    }

    #[test]
    fn single_candidate_produces_file() {
        let dir = tempfile::tempdir().unwrap();
        let synth = PytestSynthesizer::new(dir.path());
        let candidate = make_candidate(
            "def test_add():\n    assert 2 + 2 == 4",
            vec![BranchId::new(1, 10, 0, 0)],
        );
        let results = synth.synthesize(&[candidate]).unwrap();
        assert_eq!(results.len(), 1);

        let out = &results[0];
        assert!(out.path.exists());
        assert!(out.path.extension().unwrap() == "py");
        assert!(out.content.contains("Auto-generated by APEX"));
        assert!(out.content.contains("import pytest"));
        assert!(out.content.contains("def test_add()"));
        assert!(out.content.contains("assert 2 + 2 == 4"));
        assert_eq!(out.covers_branches.len(), 1);
    }

    #[test]
    fn deduplicates_identical_code() {
        let dir = tempfile::tempdir().unwrap();
        let synth = PytestSynthesizer::new(dir.path());
        let c1 = make_candidate("def test_x():\n    pass", vec![BranchId::new(1, 5, 0, 0)]);
        let c2 = make_candidate("def test_x():\n    pass", vec![BranchId::new(1, 6, 0, 0)]);
        let results = synth.synthesize(&[c1, c2]).unwrap();

        let count = results[0].content.matches("def test_x").count();
        assert_eq!(count, 1, "duplicate code should be deduplicated");
    }

    #[test]
    fn empty_code_candidate_skipped_in_content() {
        let dir = tempfile::tempdir().unwrap();
        let synth = PytestSynthesizer::new(dir.path());
        let c1 = make_candidate("   ", vec![]);
        let c2 = make_candidate("def test_real():\n    pass", vec![]);
        let results = synth.synthesize(&[c1, c2]).unwrap();
        assert_eq!(results.len(), 1);
        // The empty-code candidate should not produce a "Candidate" comment.
        assert!(results[0].content.contains("def test_real()"));
        // Only one candidate comment expected.
        let candidate_comments = results[0].content.matches("# Candidate").count();
        assert_eq!(candidate_comments, 1);
    }

    #[test]
    fn branch_targets_listed_in_comment() {
        let dir = tempfile::tempdir().unwrap();
        let synth = PytestSynthesizer::new(dir.path());
        let candidate = make_candidate(
            "def test_b():\n    pass",
            vec![BranchId::new(42, 7, 0, 0), BranchId::new(42, 8, 0, 1)],
        );
        let results = synth.synthesize(&[candidate]).unwrap();
        assert!(results[0].content.contains("42:7"));
        assert!(results[0].content.contains("42:8"));
    }

    #[test]
    fn output_in_apex_generated_subdir() {
        let dir = tempfile::tempdir().unwrap();
        let synth = PytestSynthesizer::new(dir.path());
        let candidate = make_candidate("def test_t():\n    pass", vec![]);
        let results = synth.synthesize(&[candidate]).unwrap();
        assert!(results[0]
            .path
            .parent()
            .unwrap()
            .ends_with("apex_generated"));
    }

    #[test]
    fn language_is_python() {
        let dir = tempfile::tempdir().unwrap();
        let synth = PytestSynthesizer::new(dir.path());
        assert_eq!(synth.language(), Language::Python);
    }

    #[test]
    fn multiple_candidates_branches_collected() {
        let dir = tempfile::tempdir().unwrap();
        let synth = PytestSynthesizer::new(dir.path());
        let c1 = make_candidate("def test_a():\n    pass", vec![BranchId::new(1, 1, 0, 0)]);
        let c2 = make_candidate("def test_b():\n    pass", vec![BranchId::new(2, 2, 0, 1)]);
        let results = synth.synthesize(&[c1, c2]).unwrap();
        assert_eq!(results[0].covers_branches.len(), 2);
    }
}
