use apex_core::{
    error::{ApexError, Result},
    traits::TestSynthesizer,
    types::{Language, SynthesizedTest, TestCandidate},
};
use std::{collections::HashSet, path::PathBuf};
use tracing::info;

pub struct CargoTestSynthesizer {
    output_dir: PathBuf,
    /// Name of the crate under test, used for `use <crate>::*` imports.
    crate_name: Option<String>,
}

impl CargoTestSynthesizer {
    pub fn new(output_dir: impl Into<PathBuf>) -> Self {
        CargoTestSynthesizer {
            output_dir: output_dir.into(),
            crate_name: None,
        }
    }

    pub fn with_crate_name(mut self, name: impl Into<String>) -> Self {
        self.crate_name = Some(name.into());
        self
    }

    fn generate_file_content(candidates: &[&TestCandidate], crate_name: Option<&str>) -> String {
        let mut content = String::new();
        content.push_str("// Auto-generated by APEX — do not edit by hand.\n");
        content.push_str("#![allow(unused_imports, dead_code)]\n\n");
        if let Some(name) = crate_name {
            content.push_str(&format!("use {name}::*;\n\n"));
        }
        content.push_str("#[cfg(test)]\nmod apex_generated {\n");
        if crate_name.is_some() {
            content.push_str("    use super::*;\n");
        }
        content.push('\n');

        for (i, candidate) in candidates.iter().enumerate() {
            content.push_str(&format!(
                "    // Candidate {} — covers: {}\n",
                i + 1,
                candidate
                    .target_branches
                    .iter()
                    .map(|b| format!("{}:{}", b.file_id, b.line))
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
            // Indent each line of the candidate code by 4 spaces.
            for line in candidate.code.lines() {
                content.push_str("    ");
                content.push_str(line);
                content.push('\n');
            }
            content.push('\n');
        }
        content.push_str("}\n");
        content
    }
}

impl TestSynthesizer for CargoTestSynthesizer {
    fn language(&self) -> Language {
        Language::Rust
    }

    fn synthesize(&self, candidates: &[TestCandidate]) -> Result<Vec<SynthesizedTest>> {
        if candidates.is_empty() {
            return Ok(Vec::new());
        }

        // Deduplicate by code hash.
        let mut seen: HashSet<u64> = HashSet::new();
        let mut unique: Vec<&TestCandidate> = Vec::new();
        for c in candidates {
            use std::hash::{Hash, Hasher};
            let mut h = std::collections::hash_map::DefaultHasher::new();
            c.code.hash(&mut h);
            if seen.insert(h.finish()) {
                unique.push(c);
            }
        }

        let mut outputs = Vec::new();
        for chunk in unique.chunks(10) {
            let content = Self::generate_file_content(chunk, self.crate_name.as_deref());
            let hash: u64 = {
                use std::hash::{Hash, Hasher};
                let mut h = std::collections::hash_map::DefaultHasher::new();
                content.hash(&mut h);
                h.finish()
            };
            let file_name = format!("apex_generated_{hash:016x}.rs");
            let file_path = self.output_dir.join("apex_generated").join(&file_name);

            let parent = file_path
                .parent()
                .ok_or_else(|| ApexError::Synthesis("file path has no parent dir".into()))?;
            std::fs::create_dir_all(parent)
                .map_err(|e| ApexError::Synthesis(format!("create dir: {e}")))?;

            std::fs::write(&file_path, &content)
                .map_err(|e| ApexError::Synthesis(format!("write {file_name}: {e}")))?;

            let covers = chunk
                .iter()
                .flat_map(|c| c.target_branches.clone())
                .collect();
            info!(file = %file_path.display(), "wrote Rust test file");

            outputs.push(SynthesizedTest {
                path: file_path,
                content,
                covers_branches: covers,
            });
        }
        Ok(outputs)
    }
}

/// Generate a Bolero harness that works as unit test + fuzz target + Kani proof.
pub fn bolero_harness(function_name: &str, params: &[&str]) -> String {
    let typed_params: String = params
        .iter()
        .map(|p| {
            let parts: Vec<&str> = p.split(':').collect();
            let name = parts[0].trim();
            let ty = parts.get(1).map(|t| t.trim()).unwrap_or("u32");
            format!("    let {name}: {ty} = gen.gen();")
        })
        .collect::<Vec<_>>()
        .join("\n");

    let call_args: String = params
        .iter()
        .map(|p| p.split(':').next().unwrap_or(p).trim())
        .collect::<Vec<_>>()
        .join(", ");

    format!(
        r#"#[test]
fn bolero_test_{function_name}() {{
    bolero::check!().with_type().for_each(|gen| {{
{typed_params}
        let _ = {function_name}({call_args});
    }});
}}"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use apex_core::types::BranchId;

    fn make_candidate(code: &str, branches: Vec<BranchId>) -> TestCandidate {
        let mut tc = TestCandidate::new(code.to_string(), Language::Rust);
        tc.target_branches = branches;
        tc
    }

    #[test]
    fn empty_candidates_returns_empty() {
        let dir = tempfile::tempdir().unwrap();
        let synth = CargoTestSynthesizer::new(dir.path());
        let result = synth.synthesize(&[]).unwrap();
        assert!(result.is_empty());
    }

    #[test]
    fn single_candidate_produces_file() {
        let dir = tempfile::tempdir().unwrap();
        let synth = CargoTestSynthesizer::new(dir.path());
        let candidate = make_candidate(
            "#[test]\nfn test_add() {\n    assert_eq!(2 + 2, 4);\n}",
            vec![BranchId::new(1, 10, 0, 0)],
        );
        let results = synth.synthesize(&[candidate]).unwrap();
        assert_eq!(results.len(), 1);

        let out = &results[0];
        assert!(out.path.exists());
        assert!(out.path.extension().unwrap() == "rs");
        assert!(out.content.contains("Auto-generated by APEX"));
        assert!(out.content.contains("#[cfg(test)]"));
        assert!(out.content.contains("mod apex_generated"));
        assert!(out.content.contains("assert_eq!(2 + 2, 4)"));
        assert_eq!(out.covers_branches.len(), 1);
        assert_eq!(out.covers_branches[0].line, 10);
    }

    #[test]
    fn with_crate_name_adds_use_import() {
        let dir = tempfile::tempdir().unwrap();
        let synth = CargoTestSynthesizer::new(dir.path()).with_crate_name("my_crate");
        let candidate = make_candidate("#[test]\nfn test_thing() {}", vec![]);
        let results = synth.synthesize(&[candidate]).unwrap();
        assert_eq!(results.len(), 1);
        assert!(results[0].content.contains("use my_crate::*;"));
        assert!(results[0].content.contains("use super::*;"));
    }

    #[test]
    fn without_crate_name_no_use_import() {
        let dir = tempfile::tempdir().unwrap();
        let synth = CargoTestSynthesizer::new(dir.path());
        let candidate = make_candidate("#[test]\nfn test_thing() {}", vec![]);
        let results = synth.synthesize(&[candidate]).unwrap();
        assert!(!results[0].content.contains("use super::*;"));
    }

    #[test]
    fn deduplicates_identical_code() {
        let dir = tempfile::tempdir().unwrap();
        let synth = CargoTestSynthesizer::new(dir.path());
        let c1 = make_candidate("#[test]\nfn test_dup() {}", vec![BranchId::new(1, 5, 0, 0)]);
        let c2 = make_candidate("#[test]\nfn test_dup() {}", vec![BranchId::new(1, 6, 0, 0)]);
        let results = synth.synthesize(&[c1, c2]).unwrap();

        // Only one unique candidate should appear in the content.
        let count = results[0].content.matches("test_dup").count();
        assert_eq!(count, 1, "duplicate code should be deduplicated");
    }

    #[test]
    fn multiple_candidates_branch_coverage_collected() {
        let dir = tempfile::tempdir().unwrap();
        let synth = CargoTestSynthesizer::new(dir.path());
        let c1 = make_candidate("#[test]\nfn a() {}", vec![BranchId::new(1, 10, 0, 0)]);
        let c2 = make_candidate("#[test]\nfn b() {}", vec![BranchId::new(2, 20, 0, 1)]);
        let results = synth.synthesize(&[c1, c2]).unwrap();
        assert_eq!(results.len(), 1);
        assert_eq!(results[0].covers_branches.len(), 2);
    }

    #[test]
    fn language_is_rust() {
        let dir = tempfile::tempdir().unwrap();
        let synth = CargoTestSynthesizer::new(dir.path());
        assert_eq!(synth.language(), Language::Rust);
    }

    #[test]
    fn output_placed_in_apex_generated_subdir() {
        let dir = tempfile::tempdir().unwrap();
        let synth = CargoTestSynthesizer::new(dir.path());
        let candidate = make_candidate("#[test]\nfn t() {}", vec![]);
        let results = synth.synthesize(&[candidate]).unwrap();
        assert!(results[0]
            .path
            .parent()
            .unwrap()
            .ends_with("apex_generated"));
    }

    #[test]
    fn synthesize_bolero_harness() {
        let harness = bolero_harness("check_bounds", &["x: u32", "y: u32"]);
        assert!(harness.contains("bolero::check!"));
        assert!(harness.contains("check_bounds"));
    }
}
